import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'scan': 'Scan',
      'history': 'History',
      'search': 'Search',
      'search_hint': 'Search your scanned products',
      'search_helper_text': 'Search through products you\'ve scanned or saved',
      'showing_local_results': 'Showing results from your scanned products',
      'no_local_results': 'No matching products found in your history. Try scanning new products!',
      'no_search_results': 'No products found matching your search',
      'recommendations': 'Healthier Alternatives',
      'recommendations_error': 'Error loading recommendations',
      'no_recommendations': 'Scan more products to get personalized recommendations',
      'search_examples': 'Examples: "Coca Cola", "Nutella", "Lay\'s Chips", "5449000000996"',
      'openfoodfacts_info': 'Search uses OpenFoodFacts database. If a product isn\'t found, try scanning its barcode instead.',
      'try_again': 'Try Again',
      'start_searching': 'Start typing to search products',
      'no_results': 'No products found',
      'non_food_product': 'This is not a food product',
      'non_food_product_message': 'Please scan food items only. This app is designed to analyze food products.',
      'scan_error': 'Unable to scan product',
      'scan_error_message': 'Please try again or check if the barcode is clear and well-lit.',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'settings': 'Settings',
      'dietary_preferences': 'Dietary Preferences',
      'notifications': 'Notifications',
      'notifications_enabled': 'Enable Notifications',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'about': 'About',
      'about_description': 'NutriScan helps you make informed decisions about the food you consume. Simply scan product barcodes to get detailed nutritional information, allergen alerts, and dietary compatibility.',
      'version': 'Version',
      'none_selected': 'None selected',
      'select_language': 'Select Language',
      'done': 'Done',
      'nutritional_values': 'Nutritional Values',
      'ingredients': 'Ingredients',
      'allergens': 'Allergens',
      'per_100g': 'per 100g',
      'per_serving': 'per {serving}',
      'energy': 'Energy',
      'fat': 'Fat',
      'saturated_fat': 'Saturated Fat',
      'carbohydrates': 'Carbohydrates',
      'sugars': 'Sugars',
      'proteins': 'Proteins',
      'salt': 'Salt',
      'fiber': 'Fiber',
      'product': 'Product',
      'dietary_warning': 'Dietary Preferences Warning',
      'additives': 'Additives',
      'additives_warning': 'Additives Information',
      'risk_level': 'Risk Level',
      'low_risk': 'Low Risk',
      'moderate_risk': 'Moderate Risk',
      'high_risk': 'High Risk',
      'unknown_risk': 'Unknown Risk',
      'no_additives': 'No additives found',
      'not_suitable': 'This product is not suitable for your',
      'diet': 'diet',
      'diets': 'diets',
      'vegetarian': 'Vegetarian',
      'vegan': 'Vegan',
      'gluten_free': 'Gluten-free',
      'lactose_free': 'Lactose-free',
      'nut_free': 'Nut-free',
      'palm_oil_free': 'Palm Oil Free',
      'scan_product': 'Scan Product',
      'scan_barcode': 'Scan a product barcode',
      'camera_permission': 'Camera permission is required',
      'grant_permission': 'Grant Permission',
      'search_products': 'Search Products',
      'no_favorites': 'No favorite products',
      'no_history': 'No scan history',
      'clear_history': 'Clear History',
      'clear_history_confirm': 'Are you sure you want to clear your scan history?',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'unknown_brand': 'Unknown Brand',
      'search_error': 'Error searching products',
      'bottom_nav_scan': 'Scan',
      'bottom_nav_history': 'History',
      'bottom_nav_search': 'Search',
      'bottom_nav_favorites': 'Favorites',
      'bottom_nav_profile': 'Profile',
      'bottom_nav_overview': 'Overview',
      'bottom_nav_recommendations': 'Recommendations',
      'bottom_nav_compare': 'Compare',
      'compare': 'Compare Products',
      'comparison_instructions': 'Select two products to compare their nutritional values',
      'select_product': 'Select Product',
      'no_products_to_compare': 'No products available to compare. Scan or favorite some products first.',
      'product_1_details': 'Product 1 Details',
      'product_2_details': 'Product 2 Details',
      'product_details': 'Product Details',
      'select_product_for_details': 'Select a product to view its details',
      'remove': 'Remove',
      'overview': 'Overview',
      'scan_statistics': 'Scan Statistics',
      'total_scans': 'Total Scans',
      'total_favorites': 'Total Favorites',
      'eco_friendly_products': 'Eco-friendly Products',
      'nutrition_overview': 'Nutrition Overview',
      'sign_in_message': 'Sign in to access your personalized nutrition profile and save your favorite products.',
      'sign_in_with_google': 'Sign in with Google',
      'sign_out': 'Sign Out',
      'anonymous': 'Anonymous User',
      'organic': 'Organic',
      'fair_trade': 'Fair Trade',
      'allergen_warning': 'Contains allergens',
      'may_contain': 'May contain',
      'dietary_info': 'Dietary Information',
      'certifications': 'Certifications',
      'goals': 'Goals',
      'bottom_nav_goals': 'Goals',
      'weekly_progress': 'Weekly Progress',
      'healthy_choices': 'healthy choices this week',
      'eco_friendly': 'Eco-Friendly',
      'eco_friendly_choices': 'eco-friendly choices',
      'healthy_streak': 'Healthy Streak',
      'healthy_products': 'healthy products',
      'nutriscore_distribution': 'Nutriscore Distribution',
      'tips_for_improvement': 'Tips for Improvement',
      'tip_1_title': 'Choose More A and B Products',
      'tip_1_description': 'Products with Nutriscore A and B are generally healthier choices.',
      'tip_2_title': 'Go Plant-Based',
      'tip_2_description': 'Try incorporating more vegetarian and vegan products in your diet.',
      'tip_3_title': 'Watch Additives',
      'tip_3_description': 'Choose products with fewer artificial additives when possible.',
      'education': 'Education',
      'bottom_nav_education': 'Learn',
      'education_intro': 'Learn more about nutrition, ingredients, and making healthier food choices.',
      'daily_nutrition_facts': 'Daily Nutrition Facts',
      'daily_nutrition_facts_desc': 'Learn about essential nutrients and daily recommended values.',
      'ingredient_encyclopedia': 'Ingredient Encyclopedia',
      'ingredient_encyclopedia_desc': 'Detailed information about common food ingredients and additives.',
      'understanding_labels': 'Understanding Food Labels',
      'understanding_labels_desc': 'Guide to reading and understanding nutrition labels and claims.',
      'healthy_tips': 'Tips for Healthier Choices',
      'healthy_tips_desc': 'Practical advice for making better food choices.',
      'nutrition_quizzes': 'Nutrition Quizzes',
      'nutrition_quizzes_desc': 'Test your knowledge about nutrition and food.',
      'seasonal_guide': 'Seasonal Food Guide',
      'seasonal_guide_desc': 'Learn about seasonal fruits and vegetables.',
      'eco_packaging': 'Eco-Friendly Packaging',
      'eco_packaging_desc': 'Understanding food packaging and environmental impact.',
      'feature_coming_soon': 'This feature is coming soon!',
      'daily_intake_title': 'Recommended Daily Intake',
      'daily_intake_content': 'An average adult needs approximately 2000-2500 calories per day, but this varies based on age, sex, weight, activity level, and other factors.',
      'macronutrients_title': 'Macronutrients Distribution',
      'macronutrients_content': 'A balanced diet typically consists of: 45-65% carbohydrates, 20-35% fats, and 10-35% proteins. This distribution helps maintain proper body function and energy levels.',
      'vitamins_minerals_title': 'Essential Vitamins and Minerals',
      'vitamins_minerals_content': 'Key micronutrients include vitamins A, C, D, E, K, B-complex, and minerals like iron, calcium, and zinc. These support immune function, bone health, and energy metabolism.',
      'hydration_title': 'Hydration',
      'hydration_content': 'Aim for 8-10 glasses of water daily. Hydration needs increase with exercise, heat, or illness. Monitor urine color - pale yellow indicates good hydration.',
      'additives_title': 'Food Additives',
      'additives_content': 'Additives are substances added to food for preservation or enhancement. Some are natural, while others are synthetic. Common types include preservatives, colorings, and flavor enhancers.',
      'natural_artificial_title': 'Natural vs Artificial',
      'natural_artificial_content': 'Natural ingredients come directly from plants or animals. Artificial ingredients are synthesized in laboratories. Natural isn\'t always healthier - both types should be consumed in moderation.',
      'hidden_sugars_title': 'Hidden Sugars',
      'hidden_sugars_content': 'Sugar can appear under many names: glucose, fructose, dextrose, maltose, etc. Watch for ingredients ending in "-ose" and terms like syrup, nectar, or concentrate.',
      'preservatives_title': 'Preservatives',
      'preservatives_content': 'Preservatives extend food shelf life by preventing spoilage. Common ones include sodium benzoate, potassium sorbate, and sulfites. Some people may be sensitive to certain preservatives.',
      'nutrition_panel_title': 'Nutrition Panel',
      'nutrition_panel_content': 'Shows serving size, calories, and nutrient content. Values are typically shown per 100g and per serving to help compare products.',
      'ingredient_list_title': 'Ingredient List',
      'ingredient_list_content': 'Ingredients are listed by weight, from most to least. This helps understand what makes up the majority of the product.',
      'health_claims_title': 'Health Claims',
      'health_claims_content': 'Terms like "low fat" or "high fiber" are regulated. For example, "low fat" means 3g or less per 100g for solids.',
      'allergen_info_title': 'Allergen Information',
      'allergen_info_content': 'Common allergens must be clearly labeled. They may appear in bold or in a separate "Contains" statement.',
      'balanced_plate_title': 'Balanced Plate',
      'balanced_plate_content': 'Fill half your plate with vegetables, a quarter with lean protein, and a quarter with whole grains for a balanced meal.',
      'smart_shopping_title': 'Smart Shopping',
      'smart_shopping_content': 'Shop the perimeter of the store first - that\'s where fresh, whole foods are usually found. Read labels before buying packaged foods.',
      'meal_prep_title': 'Meal Preparation',
      'meal_prep_content': 'Prepare meals ahead to avoid unhealthy convenience foods. Use herbs and spices instead of salt for flavoring.',
      'mindful_eating_title': 'Mindful Eating',
      'mindful_eating_content': 'Eat slowly, without distractions. This helps recognize satiety signals and improves digestion.',
      'spring_title': 'Spring',
      'spring_content': 'Look for asparagus, peas, strawberries, and leafy greens. These foods are naturally rich in vitamins and minerals needed for energy as days get longer.',
      'summer_title': 'Summer',
      'summer_content': 'Enjoy tomatoes, peppers, berries, and stone fruits. Summer produce is rich in antioxidants and naturally hydrating.',
      'fall_title': 'Fall',
      'fall_content': 'Choose pumpkins, apples, pears, and root vegetables. These foods provide sustained energy and immune support for cooler weather.',
      'winter_title': 'Winter',
      'winter_content': 'Select citrus fruits, winter squash, and cruciferous vegetables. These foods are rich in vitamin C and other nutrients to support winter health.',
      'packaging_symbols_title': 'Packaging Symbols',
      'packaging_symbols_content': 'Learn to identify recyclable materials through packaging symbols. The number inside the recycling symbol indicates the type of plastic used.',
      'sustainable_materials_title': 'Sustainable Materials',
      'sustainable_materials_content': 'Look for products in glass, aluminum, or cardboard packaging. These materials have high recycling rates and lower environmental impact.',
      'reducing_waste_title': 'Reducing Waste',
      'reducing_waste_content': 'Choose products with minimal packaging or bulk options. Bring reusable bags and containers when shopping.',
      'proper_disposal_title': 'Proper Disposal',
      'proper_disposal_content': 'Clean containers before recycling. Different materials may need to be separated. Check local recycling guidelines for specific requirements.',
      'product_details_singular': 'Product Details',
      'product_details_plural': 'Product Details',
      'other_high_risk_additives': 'Other High-Risk Additives',
      'other_high_risk_additives_desc': '{count} additional high-risk additives or sweeteners',
      'other_moderate_risk_additives': 'Other Moderate-Risk Additives',
      'other_moderate_risk_additives_desc': '{count} additional moderate-risk additives',
      'other_low_risk_additives': 'Other Low-Risk Additives',
      'other_low_risk_additives_desc': '{count} additional low-risk additives',
      'unidentified': 'Unidentified',
      'sweetener': 'Sweetener',
      'color': 'Color',
      'preservative': 'Preservative',
      'antioxidant': 'Antioxidant',
      'emulsifier': 'Emulsifier',
      'thickener': 'Thickener',
      'stabilizer': 'Stabilizer',
      'acid': 'Acid',
      'flavoring': 'Flavoring',
      'additive': 'Additive',
      'no_ingredients': 'No ingredients listed',
      'themes': 'Themes',
      'select_theme': 'Set Theme',
      'purple': 'Purple',
      'green': 'Green',
      'orange': 'Orange',
      'blue': 'Blue',
      'grey': 'Grey',
      'sign_in': 'Sign In',
      'sign_out': 'Sign Out',
    },
    'es': {
      'scan': 'Escanear',
      'history': 'Historial',
      'search': 'Buscar',
      'search_hint': 'Buscar tus productos escaneados',
      'search_helper_text': 'Try entering a product name (e.g., "Oreo") or brand name (e.g., "Nestle")',
      'search_examples': 'Examples: "Coca Cola", "Nutella", "Lay\'s Chips", "5449000000996"',
      'openfoodfacts_info': 'Search uses OpenFoodFacts database. If a product isn\'t found, try scanning its barcode instead.',
      'try_again': 'Intentar de Nuevo',
      'start_searching': 'Empiece a escribir para buscar productos',
      'no_results': 'No se encontraron productos',
      'favorites': 'Favoritos',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'dietary_preferences': 'Preferencias Dietéticas',
      'notifications': 'Notificaciones',
      'notifications_enabled': 'Habilitar Notificaciones',
      'language': 'Idioma',
      'dark_mode': 'Modo Oscuro',
      'about': 'Acerca de',
      'about_description': 'NutriScan te ayuda a tomar decisiones informadas sobre los alimentos que consumes. Simplemente escanea códigos de barras de productos para obtener información nutricional detallada, alertas de alérgenos y compatibilidad dietética.',
      'version': 'Versión',
      'none_selected': 'Ninguno seleccionado',
      'select_language': 'Seleccionar Idioma',
      'done': 'Listo',
      'nutritional_values': 'Valores Nutricionales',
      'ingredients': 'Ingredientes',
      'allergens': 'Alérgenos',
      'per_100g': 'por 100g',
      'per_serving': 'por {serving}',
      'energy': 'Energía',
      'fat': 'Grasas',
      'saturated_fat': 'Grasas Saturadas',
      'carbohydrates': 'Carbohidratos',
      'sugars': 'Azúcares',
      'proteins': 'Proteínas',
      'salt': 'Sal',
      'fiber': 'Fibra',
      'dietary_warning': 'Advertencia de Preferencias Dietéticas',
      'additives': 'Aditivos',
      'additives_warning': 'Información de Aditivos',
      'risk_level': 'Nivel de Riesgo',
      'low_risk': 'Bajo Riesgo',
      'moderate_risk': 'Riesgo Moderado',
      'high_risk': 'Alto Riesgo',
      'unknown_risk': 'Riesgo Desconocido',
      'no_additives': 'No se encontraron aditivos',
      'not_suitable': 'Este producto no es apto para tu',
      'diet': 'dieta',
      'diets': 'dietas',
      'vegetarian': 'Vegetariano',
      'vegan': 'Vegano',
      'gluten_free': 'Sin Gluten',
      'lactose_free': 'Sin Lactosa',
      'nut_free': 'Sin Frutos Secos',
      'palm_oil_free': 'Sin Aceite de Palma',
      'scan_product': 'Escanear Producto',
      'scan_barcode': 'Escanea el código de barras de un producto',
      'camera_permission': 'Se requiere permiso de cámara',
      'grant_permission': 'Conceder Permiso',
      'search_products': 'Buscar Productos',
      'no_favorites': 'No hay productos favoritos',
      'no_history': 'No hay historial de escaneo',
      'clear_history': 'Borrar Historial',
      'clear_history_confirm': '¿Estás seguro de que quieres borrar el historial de escaneo?',
      'cancel': 'Cancelar',
      'clear': 'Borrar',
      'unknown_brand': 'Marca Desconocida',
      'search_error': 'Error al buscar productos',
      'bottom_nav_scan': 'Escanear',
      'bottom_nav_history': 'Historial',
      'bottom_nav_search': 'Buscar',
      'bottom_nav_favorites': 'Favoritos',
      'bottom_nav_profile': 'Perfil',
      'bottom_nav_overview': 'Resumen',
      'bottom_nav_recommendations': 'Recomendaciones',
      'bottom_nav_compare': 'Comparar',
      'compare': 'Comparar Productos',
      'comparison_instructions': 'Selecciona dos productos para comparar sus valores nutricionales',
      'select_product': 'Seleccionar Producto',
      'no_products_to_compare': 'No hay productos disponibles para comparar. Escanea o marca como favoritos algunos productos primero.',
      'product_1_details': 'Detalles del Producto 1',
      'product_2_details': 'Detalles del Producto 2',
      'product_details': 'Detalles del Producto',
      'select_product_for_details': 'Seleccione un producto para ver sus detalles',
      'remove': 'Eliminar',
      'overview': 'Resumen',
      'scan_statistics': 'Estadísticas de Escaneo',
      'total_scans': 'Escaneos Totales',
      'total_favorites': 'Favoritos Totales',
      'eco_friendly_products': 'Productos Ecológicos',
      'nutrition_overview': 'Resumen Nutricional',
      'organic': 'Orgánico',
      'fair_trade': 'Comercio Justo',
      'allergen_warning': 'Contiene alérgenos',
      'may_contain': 'Puede contener',
      'dietary_info': 'Información Dietética',
      'certifications': 'Certificaciones',
      'goals': 'Objetivos',
      'bottom_nav_goals': 'Objetivos',
      'weekly_progress': 'Progreso Semanal',
      'healthy_choices': 'elecciones saludables esta semana',
      'eco_friendly': 'Ecológico',
      'eco_friendly_choices': 'elecciones ecológicas',
      'healthy_streak': 'Racha Saludable',
      'healthy_products': 'productos saludables',
      'nutriscore_distribution': 'Distribución Nutriscore',
      'tips_for_improvement': 'Consejos para Mejorar',
      'tip_1_title': 'Elige Más Productos A y B',
      'tip_1_description': 'Los productos con Nutriscore A y B son generalmente más saludables.',
      'tip_2_title': 'Opta por Vegetales',
      'tip_2_description': 'Intenta incorporar más productos vegetarianos y veganos en tu dieta.',
      'tip_3_title': 'Controla los Aditivos',
      'tip_3_description': 'Elige productos con menos aditivos artificiales cuando sea posible.',
      'education': 'Educación',
      'bottom_nav_education': 'Aprender',
      'education_intro': 'Aprenda más sobre nutrición, ingredientes y hacer mejores elecciones alimenticias.',
      'daily_nutrition_facts': 'Hechos Nutricionales Diarios',
      'daily_nutrition_facts_desc': 'Aprenda sobre los nutrientes esenciales y los valores recomendados diariamente.',
      'ingredient_encyclopedia': 'Enciclopedia de Ingredientes',
      'ingredient_encyclopedia_desc': 'Información detallada sobre los ingredientes alimenticios comunes y los aditivos.',
      'understanding_labels': 'Entendiendo las Etiquetas de Alimentos',
      'understanding_labels_desc': 'Guía para leer y entender las etiquetas y reclamaciones de la nutrición.',
      'healthy_tips': 'Consejos para Elecciones Más Sanas',
      'healthy_tips_desc': 'Consejos prácticos para hacer mejores elecciones alimenticias.',
      'nutrition_quizzes': 'Cuadernos de Nutrición',
      'nutrition_quizzes_desc': 'Pruebe su conocimiento sobre nutrición y alimentos.',
      'seasonal_guide': 'Guía de Alimentos Estacionales',
      'seasonal_guide_desc': 'Aprenda sobre frutas y verduras estacionales.',
      'eco_packaging': 'Empaque Ecológico',
      'eco_packaging_desc': 'Entendiendo el empaque de alimentos y su impacto ambiental.',
      'feature_coming_soon': 'Esta característica está por venir!',
      'daily_intake_title': 'Ingesta Diaria Recomendada',
      'daily_intake_content': 'Un adulto promedio necesita aproximadamente 2000-2500 calorías por día, pero esto varía según la edad, el sexo, el peso, el nivel de actividad y otros factores.',
      'macronutrients_title': 'Distribución de Macronutrientes',
      'macronutrients_content': 'Una dieta equilibrada típicamente consiste en: 45-65% carbohidratos, 20-35% grasas y 10-35% proteínas. Esta distribución ayuda a mantener un funcionamiento corporal adecuado y niveles de energía.',
      'vitamins_minerals_title': 'Vitaminas y Minerales Esenciales',
      'vitamins_minerals_content': 'Los micronutrientes clave incluyen Vitamina D, B12, Hierro, Calcio y Zinc. Estos apoyan la función inmune, la salud ósea y el metabolismo energético.',
      'hydration_title': 'Hidratación',
      'hydration_content': 'Trata de beber 8 vasos (aproximadamente 2 litros) de agua al día. Los requerimientos aumentan con el ejercicio, el clima cálido o ciertas condiciones médicas.',
      'additives_title': 'Aditivos Comunes',
      'additives_content': 'Los números E son códigos para aditivos alimentarios. Aunque muchos son seguros, algunos pueden causar reacciones en personas sensibles. Los más comunes incluyen E330 (Ácido Cítrico) y E300 (Vitamina C).',
      'natural_artificial_title': 'Natural vs. Artificial',
      'natural_artificial_content': 'Los ingredientes naturales provienen directamente de plantas o animales. Los ingredientes artificiales se sintetizan en laboratorios. Ninguno es inherentemente bueno o malo - la seguridad depende de propiedades específicas y uso.',
      'hidden_sugars_title': 'Azúcares Ocultos',
      'hidden_sugars_content': 'El azúcar puede aparecer bajo muchos nombres: glucosa, fructosa, dextrosa, maltosa, jarabe de maíz y más. Estar consciente ayuda a monitorear la ingesta total de azúcar.',
      'preservatives_title': 'Conservantes',
      'preservatives_content': 'Los conservantes comunes incluyen sulfitos, nitritos y benzoatos. Si bien mantienen los alimentos seguros por más tiempo, algunas personas pueden ser sensibles a ciertos tipos.',
      'nutrition_panel_title': 'Panel de Información Nutricional',
      'nutrition_panel_content': 'Muestra el tamaño de la porción, calorías y contenido de nutrientes. Los valores se muestran típicamente por 100g y por porción para ayudar a comparar productos.',
      'ingredient_list_title': 'Lista de Ingredientes',
      'ingredient_list_content': 'Los ingredientes se enumeran por peso, de mayor a menor. Esto ayuda a entender qué compone la mayoría del producto.',
      'health_claims_title': 'Declaraciones de Salud',
      'health_claims_content': 'Términos como "bajo en grasa" o "alto en fibra" están regulados. Por ejemplo, "bajo en grasa" significa 3g o menos por 100g para sólidos.',
      'allergen_info_title': 'Información sobre Alérgenos',
      'allergen_info_content': 'Los alérgenos comunes deben estar claramente etiquetados. Pueden aparecer en negrita o en una declaración separada de "Contiene".',
      'balanced_plate_title': 'Plato Equilibrado',
      'balanced_plate_content': 'Llena la mitad de tu plato con verduras, un cuarto con proteínas magras y un cuarto con granos integrales para una comida equilibrada.',
      'smart_shopping_title': 'Compra Inteligente',
      'smart_shopping_content': 'Compra primero en el perímetro de la tienda - ahí es donde generalmente se encuentran los alimentos frescos y enteros. Lee las etiquetas antes de comprar alimentos envasados.',
      'meal_prep_title': 'Preparación de Comidas',
      'meal_prep_content': 'Prepara las comidas con anticipación para evitar alimentos poco saludables por conveniencia. Usa hierbas y especias en lugar de sal para dar sabor.',
      'mindful_eating_title': 'Alimentación Consciente',
      'mindful_eating_content': 'Come lentamente, sin distracciones. Esto ayuda a reconocer las señales de saciedad y mejora la digestión.',
      'spring_title': 'Primavera',
      'spring_content': 'Busca espárragos, guisantes, fresas y verduras de hoja verde. Estos alimentos son naturalmente ricos en vitaminas y minerales necesarios para la energía cuando los días se alargan.',
      'summer_title': 'Verano',
      'summer_content': 'Disfruta de tomates, pimientos, bayas y frutas de hueso. Los productos de verano son ricos en antioxidantes y naturalmente hidratantes.',
      'fall_title': 'Otoño',
      'fall_content': 'Elige calabazas, manzanas, peras y vegetales de raíz. Estos alimentos proporcionan energía sostenida y apoyo inmunológico para el clima más frío.',
      'winter_title': 'Invierno',
      'winter_content': 'Selecciona cítricos, calabaza de invierno y vegetales crucíferos. Estos alimentos son ricos en vitamina C y otros nutrientes para apoyar la salud en invierno.',
      'packaging_symbols_title': 'Símbolos de Empaque',
      'packaging_symbols_content': 'Aprende a identificar materiales reciclables a través de símbolos de empaque. El número dentro del símbolo de reciclaje indica el tipo de plástico utilizado.',
      'sustainable_materials_title': 'Materiales Sostenibles',
      'sustainable_materials_content': 'Busca productos en envases de vidrio, aluminio o cartón. Estos materiales tienen altas tasas de reciclaje y menor impacto ambiental.',
      'reducing_waste_title': 'Reducción de Residuos',
      'reducing_waste_content': 'Elige productos con empaque mínimo u opciones a granel. Trae bolsas y contenedores reutilizables cuando vayas de compras.',
      'proper_disposal_title': 'Eliminación Adecuada',
      'proper_disposal_content': 'Limpia los contenedores antes de reciclar. Diferentes materiales pueden necesitar ser separados. Consulta las pautas locales de reciclaje para requisitos específicos.',
      'product_details_singular': 'Detalles del Producto',
      'product_details_plural': 'Detalles de los Productos',
      'other_high_risk_additives': 'Otros Aditivos de Alto Riesgo',
      'other_high_risk_additives_desc': '{count} aditivos o edulcorantes adicionales de alto riesgo',
      'other_moderate_risk_additives': 'Otros Aditivos de Riesgo Moderado',
      'other_moderate_risk_additives_desc': '{count} aditivos adicionales de riesgo moderado',
      'other_low_risk_additives': 'Otros Aditivos de Bajo Riesgo',
      'other_low_risk_additives_desc': '{count} aditivos adicionales de bajo riesgo',
      'unidentified': 'No Identificado',
      'sweetener': 'Edulcorante',
      'color': 'Colorante',
      'preservative': 'Conservante',
      'antioxidant': 'Antioxidante',
      'emulsifier': 'Emulsionante',
      'thickener': 'Espesante',
      'stabilizer': 'Estabilizador',
      'acid': 'Ácido',
      'flavoring': 'Saborizante',
      'additive': 'Aditivo',
      'no_ingredients': 'No hay ingredientes listados',
      'themes': 'Temas',
      'select_theme': 'Establecer Tema',
      'purple': 'Morado',
      'green': 'Verde',
      'orange': 'Naranja',
      'blue': 'Azul',
      'grey': 'Gris',
      'sign_in': 'Iniciar Sesión',
      'sign_out': 'Cerrar Sesión',
    },
    'fr': {
      'scan': 'Scanner',
      'history': 'Historique',
      'search': 'Rechercher',
      'search_hint': 'Rechercher vos produits scannés',
      'search_helper_text': 'Try entering a product name (e.g., "Oreo") or brand name (e.g., "Nestle")',
      'search_examples': 'Examples: "Coca Cola", "Nutella", "Lay\'s Chips", "5449000000996"',
      'openfoodfacts_info': 'Search uses OpenFoodFacts database. If a product isn\'t found, try scanning its barcode instead.',
      'try_again': 'Réessayer',
      'start_searching': 'Commencez à taper pour rechercher des produits',
      'no_results': 'Aucun produit trouvé',
      'favorites': 'Favoris',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'dietary_preferences': 'Préférences Alimentaires',
      'notifications': 'Notifications',
      'notifications_enabled': 'Activer les Notifications',
      'language': 'Langue',
      'dark_mode': 'Mode Sombre',
      'about': 'À Propos',
      'about_description': 'NutriScan vous aide à prendre des décisions éclairées sur les aliments que vous consommez. Scannez simplement les codes-barres des produits pour obtenir des informations nutritionnelles détaillées, des alertes allergènes et la compatibilité alimentaire.',
      'version': 'Version',
      'none_selected': 'Aucune sélection',
      'select_language': 'Choisir la Langue',
      'done': 'Terminé',
      'nutritional_values': 'Valeurs Nutritionnelles',
      'ingredients': 'Ingrédients',
      'allergens': 'Allergènes',
      'per_100g': 'pour 100g',
      'per_serving': 'pour {serving}',
      'energy': 'Énergie',
      'fat': 'Matières Grasses',
      'saturated_fat': 'Acides Gras Saturés',
      'carbohydrates': 'Glucides',
      'sugars': 'Sucres',
      'proteins': 'Protéines',
      'salt': 'Sel',
      'fiber': 'Fibres',
      'dietary_warning': 'Avertissement Alimentaire',
      'additives': 'Additifs',
      'additives_warning': 'Information sur les Additifs',
      'risk_level': 'Niveau de Risque',
      'low_risk': 'Faible Risque',
      'moderate_risk': 'Risque Modéré',
      'high_risk': 'Risque Élevé',
      'unknown_risk': 'Risque Inconnu',
      'no_additives': 'Aucun additif trouvé',
      'not_suitable': 'Ce produit ne convient pas à votre',
      'diet': 'régime',
      'diets': 'régimes',
      'vegetarian': 'Végétarien',
      'vegan': 'Végétalien',
      'gluten_free': 'Sans Gluten',
      'lactose_free': 'Sans Lactose',
      'nut_free': 'Sans Fruits à Coque',
      'palm_oil_free': 'Sans Huile de Palme',
      'scan_product': 'Scanner un Produit',
      'scan_barcode': 'Scannez un code-barres',
      'camera_permission': 'Permission de caméra requise',
      'grant_permission': 'Autoriser',
      'search_products': 'Rechercher des Produits',
      'no_favorites': 'Aucun produit favori',
      'no_history': 'Aucun historique',
      'clear_history': 'Effacer l\'historique',
      'clear_history_confirm': 'Voulez-vous vraiment effacer l\'historique de scan ?',
      'cancel': 'Annuler',
      'clear': 'Effacer',
      'unknown_brand': 'Marque Inconnue',
      'search_error': 'Erreur lors de la recherche',
      'bottom_nav_scan': 'Scanner',
      'bottom_nav_history': 'Historique',
      'bottom_nav_search': 'Rechercher',
      'bottom_nav_favorites': 'Favoris',
      'bottom_nav_profile': 'Profil',
      'bottom_nav_overview': 'Aperçu',
      'bottom_nav_recommendations': 'Recommandations',
      'bottom_nav_compare': 'Comparer',
      'compare': 'Comparer les Produits',
      'comparison_instructions': 'Sélectionnez deux produits pour comparer leurs valeurs nutritionnelles',
      'select_product': 'Sélectionner un Produit',
      'no_products_to_compare': 'Aucun produit disponible à comparer. Scannez ou ajoutez des produits aux favoris d\'abord.',
      'product_1_details': 'Détails du Produit 1',
      'product_2_details': 'Détails du Produit 2',
      'product_details': 'Détails du Produit',
      'select_product_for_details': 'Sélectionnez un produit pour voir ses détails',
      'remove': 'Retirer',
      'overview': 'Aperçu',
      'scan_statistics': 'Statistiques de Scan',
      'total_scans': 'Scans Totaux',
      'total_favorites': 'Favoris Totaux',
      'eco_friendly_products': 'Produits Écologiques',
      'nutrition_overview': 'Aperçu Nutritionnel',
      'organic': 'Bio',
      'fair_trade': 'Commerce Équitable',
      'allergen_warning': 'Contient des allergènes',
      'may_contain': 'Peut contenir',
      'dietary_info': 'Information Diététique',
      'certifications': 'Certifications',
      'goals': 'Objectifs',
      'bottom_nav_goals': 'Objectifs',
      'weekly_progress': 'Progrès Hebdomadaire',
      'healthy_choices': 'choix sains cette semaine',
      'eco_friendly': 'Écologique',
      'eco_friendly_choices': 'choix écologiques',
      'healthy_streak': 'Série Santé',
      'healthy_products': 'produits sains',
      'nutriscore_distribution': 'Distribution Nutriscore',
      'tips_for_improvement': 'Conseils d\'Amélioration',
      'tip_1_title': 'Choisir Plus de Produits A et B',
      'tip_1_description': 'Les produits avec Nutriscore A et B sont généralement plus sains.',
      'tip_2_title': 'Opter pour le Végétal',
      'tip_2_description': 'Essayez d\'incorporer plus de produits végétariens et végans dans votre alimentation.',
      'tip_3_title': 'Surveiller les Additifs',
      'tip_3_description': 'Choisissez des produits avec moins d\'additifs artificiels quand c\'est possible.',
      'education': 'Éducation',
      'bottom_nav_education': 'Apprendre',
      'education_intro': 'Apprenez-en plus sur la nutrition, les ingrédients et les choix alimentaires plus sains.',
      'daily_nutrition_facts': 'Faits Nutritionnels Journaux',
      'daily_nutrition_facts_desc': 'Apprenez-en plus sur les nutriments essentiels et les valeurs recommandées quotidiennes.',
      'ingredient_encyclopedia': 'Encyclopédie des Ingrédients',
      'ingredient_encyclopedia_desc': 'Informations détaillées sur les ingrédients alimentaires courants et les additifs.',
      'understanding_labels': 'Comprendre les Étiquettes Alimentaires',
      'understanding_labels_desc': 'Guide pour lire et comprendre les étiquettes et les revendications nutritionnelles.',
      'healthy_tips': 'Conseils pour des Choix Plus Sains',
      'healthy_tips_desc': 'Conseils práticos pour faire de meilleurs choix alimentaires.',
      'nutrition_quizzes': 'Quiz Nutritionnels',
      'nutrition_quizzes_desc': 'Testez vos connaissances sur la nutrition et les aliments.',
      'seasonal_guide': 'Guide Alimentaire Saisonnier',
      'seasonal_guide_desc': 'Apprenez-en plus sur les fruits et légumes saisonniers.',
      'eco_packaging': 'Emballage Écologique',
      'eco_packaging_desc': 'Comprendre l\'emballage alimentaire et son impact sur l\'environnement.',
      'feature_coming_soon': 'Cette fonction est en cours de développement!',
      'daily_intake_title': 'Apport Quotidien Recommandé',
      'daily_intake_content': 'Un adulte moyen a besoin d\'environ 2000-2500 calories par jour, mais cela varie selon l\'âge, le sexe, le poids, le niveau d\'activité et d\'autres facteurs.',
      'macronutrients_title': 'Distribution des Macronutriments',
      'macronutrients_content': 'Un régime équilibré se compose généralement de : 45-65% de glucides, 20-35% de lipides et 10-35% de protéines. Cette répartition aide à maintenir un bon fonctionnement corporel et des niveaux d\'énergie.',
      'vitamins_minerals_title': 'Vitamines et Minéraux Essentiels',
      'vitamins_minerals_content': 'Les micronutriments clés comprennent la vitamine D, B12, le fer, le calcium et le zinc. Ils soutiennent la fonction immunitaire, la santé des os et le métabolisme énergétique.',
      'hydration_title': 'Hydratation',
      'hydration_content': 'Visez 8 verres (environ 2 litres) d\'eau par jour. Les besoins augmentent avec l\'exercice, la chaleur ou certaines conditions médicales.',
      'additives_title': 'Additifs Courants',
      'additives_content': 'Les numéros E sont des codes pour les additifs alimentaires. Bien que beaucoup soient sûrs, certains peuvent provoquer des réactions chez les personnes sensibles. Les plus courants incluent E330 (Acide Citrique) et E300 (Vitamine C).',
      'natural_artificial_title': 'Naturel vs. Artificiel',
      'natural_artificial_content': 'Les ingrédients naturels proviennent directement des plantes ou des animaux. Les ingrédients artificiels sont synthétisés en laboratoire. Aucun n\'est intrinsèquement bon ou mauvais - la sécurité dépend des propriétés spécifiques et de l\'utilisation.',
      'hidden_sugars_title': 'Sucres Cachés',
      'hidden_sugars_content': 'Le sucre peut apparaître sous de nombreux noms : glucose, fructose, dextrose, maltose, sirop de maïs, et plus. Être conscient aide à surveiller l\'apport total en sucre.',
      'preservatives_title': 'Conservateurs',
      'preservatives_content': 'Les conservateurs courants incluent les sulfites, les nitrites et les benzoates. Embora mantenham os alimentos seguros por mais tempo, algumas pessoas podem ser sensíveis a certos tipos.',
      'nutrition_panel_title': 'Tableau Nutritionnel',
      'nutrition_panel_content': 'Montre la taille des portions, les calories et le contenu en nutriments. Les valeurs sont généralement indiquées pour 100g et par portion pour aider à comparer les produits.',
      'ingredient_list_title': 'Liste des Ingrédients',
      'ingredient_list_content': 'Les ingrédients sont listés par poids, du plus au moins important. Cela aide à comprendre ce qui compose la majorité du produit.',
      'health_claims_title': 'Allégations Santé',
      'health_claims_content': 'Les termes comme "faible en gras" ou "riche en fibres" sont réglementés. Par exemple, "faible en gras" signifie 3g ou moins pour 100g de solides.',
      'allergen_info_title': 'Information sur les Allergènes',
      'allergen_info_content': 'Les allergènes courants doivent être clairement étiquetés. Ils peuvent apparaître en gras ou dans une déclaration "Contient" séparée.',
      'balanced_plate_title': 'Assiette Équilibrée',
      'balanced_plate_content': 'Remplissez la moitié de votre assiette de légumes, un quart de protéines maigres et un quart de céréales complètes pour un repas équilibré.',
      'smart_shopping_title': 'Achats Intelligents',
      'smart_shopping_content': 'Faites d\'abord vos courses en périphérie du magasin - c\'est là que se trouvent généralement les aliments frais et entiers. Lisez les étiquettes avant d\'acheter des aliments emballés.',
      'meal_prep_title': 'Préparation des Repas',
      'meal_prep_content': 'Préparez les repas à l\'avance pour éviter les aliments malsains de commodité. Utilisez des herbes et des épices au lieu du sel pour assaisonner.',
      'mindful_eating_title': 'Alimentation Consciente',
      'mindful_eating_content': 'Mangez lentement, sans distraction. Cela aide à reconnaître les signaux de satiété et améliore la digestion.',
      'spring_title': 'Printemps',
      'spring_content': 'Recherchez les asperges, les pois, les fraises et les légumes verts. Ces aliments sont naturellement riches en vitamines et minéraux nécessaires pour l\'énergie lorsque les jours s\'allongent.',
      'summer_title': 'Été',
      'summer_content': 'Profitez des tomates, poivrons, baies et fruits à noyau. Les produits d\'été sont riches en antioxydants et naturalement hydratants.',
      'fall_title': 'Automne',
      'fall_content': 'Choisissez les citrouilles, pommes, peras et légumes-racines. Esses aliments fournissent une énergie soutenue et un soutien immunitaire pour le temps plus frais.',
      'winter_title': 'Hiver',
      'winter_content': 'Sélectionnez les agrumes, courges d\'hiver et légumes crucifères. Ces aliments sont riches en vitamine C et autres nutriments pour soutenir la santé en hiver.',
      'packaging_symbols_title': 'Symboles d\'Emballage',
      'packaging_symbols_content': 'Apprenez à identifier les matériaux recyclables grâce aux symboles d\'emballage. Le numéro dans le symbole de recyclage indique le type de plástique utilisé.',
      'sustainable_materials_title': 'Matériaux Durables',
      'sustainable_materials_content': 'Recherchez des produits dans des emballages en verre, aluminium ou carton. Ces matériaux ont des taux de recyclage élevés et un impact environnemental moindre.',
      'reducing_waste_title': 'Réduction des Déchets',
      'reducing_waste_content': 'Choisissez des produits avec un emballage minimal ou des options en vrac. Apportez des sacs et contenants réutilisables lors des courses.',
      'proper_disposal_title': 'Élimination Appropriée',
      'proper_disposal_content': 'Nettoyez les contenants avant de recycler. Diférents matériaux peuvent nécessiter d\'être séparés. Consultez les directives locales de recyclage pour les exigences spécifiques.',
      'product_details_singular': 'Détails du Produit',
      'product_details_plural': 'Détails des Produits',
      'other_high_risk_additives': 'Autres Additifs à Haut Risque',
      'other_high_risk_additives_desc': '{count} additifs ou édulcorants supplémentaires à haut risque',
      'other_moderate_risk_additives': 'Autres Additifs à Risque Modéré',
      'other_moderate_risk_additives_desc': '{count} additifs supplémentaires à risque modéré',
      'other_low_risk_additives': 'Autres Additifs à Faible Risque',
      'other_low_risk_additives_desc': '{count} additifs supplémentaires à faible risque',
      'unidentified': 'Non Identifié',
      'sweetener': 'Édulcorant',
      'color': 'Colorant',
      'preservative': 'Conservateur',
      'antioxidant': 'Antioxidante',
      'emulsifier': 'Émulsifiant',
      'thickener': 'Épaississant',
      'stabilizer': 'Stabilisant',
      'acid': 'Acide',
      'flavoring': 'Arôme',
      'additive': 'Additif',
      'no_ingredients': 'Aucun ingrédient listé',
      'themes': 'Thèmes',
      'select_theme': 'Définir le Thème',
      'purple': 'Violet',
      'green': 'Vert',
      'orange': 'Orange',
      'blue': 'Bleu',
      'grey': 'Gris',
      'sign_in': 'Se Connecter',
      'sign_out': 'Se Déconnecter',
    },
    'de': {
      'scan': 'Scannen',
      'history': 'Verlauf',
      'search': 'Suchen',
      'search_hint': 'Durchsuchen Sie Ihre gescannten Produkte',
      'search_helper_text': 'Try entering a product name (e.g., "Oreo") or brand name (e.g., "Nestle")',
      'search_examples': 'Examples: "Coca Cola", "Nutella", "Lay\'s Chips", "5449000000996"',
      'openfoodfacts_info': 'Search uses OpenFoodFacts database. If a product isn\'t found, try scanning its barcode instead.',
      'try_again': 'Erneut Versuchen',
      'start_searching': 'Beginnen Sie mit der Eingabe, um Produkte zu suchen',
      'no_results': 'Keine Produkte gefunden',
      'favorites': 'Favoriten',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'dietary_preferences': 'Ernährungspräferenzen',
      'notifications': 'Benachrichtigungen',
      'notifications_enabled': 'Benachrichtigungen aktivieren',
      'language': 'Sprache',
      'dark_mode': 'Dunkelmodus',
      'about': 'Über',
      'about_description': 'NutriScan hilft Ihnen, fundierte Entscheidungen über die Lebensmittel zu treffen, die Sie konsumieren. Scannen Sie einfach Produkt-Barcodes, um detaillierte Nährwertinformationen, Allergen-Warnungen und Ernährungsverträglichkeit zu erhalten.',
      'version': 'Version',
      'none_selected': 'Keine Auswahl',
      'select_language': 'Sprache Auswählen',
      'done': 'Fertig',
      'nutritional_values': 'Nährwerte',
      'ingredients': 'Zutaten',
      'allergens': 'Allergene',
      'per_100g': 'pro 100g',
      'per_serving': 'pro {serving}',
      'energy': 'Energie',
      'fat': 'Fett',
      'saturated_fat': 'Gesättigte Fettsäuren',
      'carbohydrates': 'Kohlenhydrate',
      'sugars': 'Zucker',
      'proteins': 'Eiweiß',
      'salt': 'Salz',
      'fiber': 'Ballaststoffe',
      'dietary_warning': 'Warnung zu Ernährungspräferenzen',
      'additives': 'Zusatzstoffe',
      'additives_warning': 'Zusatzstoffinformation',
      'risk_level': 'Risikostufe',
      'low_risk': 'Niedriges Risiko',
      'moderate_risk': 'Mittleres Risiko',
      'high_risk': 'Hohes Risiko',
      'unknown_risk': 'Unbekanntes Risiko',
      'no_additives': 'Keine Zusatzstoffe gefunden',
      'not_suitable': 'Dieses Produkt ist nicht geeignet für Ihre',
      'diet': 'Ernährungsform',
      'diets': 'Ernährungsformen',
      'vegetarian': 'Vegetarisch',
      'vegan': 'Vegan',
      'gluten_free': 'Glutenfrei',
      'lactose_free': 'Laktosefrei',
      'nut_free': 'Nussfrei',
      'palm_oil_free': 'Ohne Palmöl',
      'scan_product': 'Produkt Scannen',
      'scan_barcode': 'Scannen Sie einen Produkt-Barcode',
      'camera_permission': 'Kameraerlaubnis erforderlich',
      'grant_permission': 'Erlaubnis Erteilen',
      'search_products': 'Produkte Suchen',
      'no_favorites': 'Keine Favoriten',
      'no_history': 'Kein Scan-Verlauf',
      'clear_history': 'Verlauf Löschen',
      'clear_history_confirm': 'Sind Sie sicher, dass Sie den Scan-Verlauf löschen möchten?',
      'cancel': 'Abbrechen',
      'clear': 'Löschen',
      'unknown_brand': 'Unbekannte Marke',
      'search_error': 'Fehler bei der Suche',
      'bottom_nav_scan': 'Scannen',
      'bottom_nav_history': 'Verlauf',
      'bottom_nav_search': 'Suchen',
      'bottom_nav_favorites': 'Favoriten',
      'bottom_nav_profile': 'Profil',
      'bottom_nav_overview': 'Übersicht',
      'bottom_nav_recommendations': 'Empfehlungen',
      'bottom_nav_compare': 'Vergleichen',
      'compare': 'Produkte Vergleichen',
      'comparison_instructions': 'Wählen Sie zwei Produkte aus, um ihre Nährwertinformationen zu vergleichen',
      'select_product': 'Produkt Auswählen',
      'no_products_to_compare': 'Keine Produkte verfügbar zum Vergleichen. Scannen Sie oder markieren Sie zuerst einige Produkte als Favoriten',
      'product_1_details': 'Produkt 1 Details',
      'product_2_details': 'Produkt 2 Details',
      'product_details': 'Produkt Details',
      'select_product_for_details': 'Wählen Sie ein Produkt aus, um dessen Details anzuzeigen',
      'remove': 'Entfernen',
      'overview': 'Übersicht',
      'scan_statistics': 'Scan-Statistiken',
      'total_scans': 'Gesamte Scans',
      'total_favorites': 'Gesamte Favoriten',
      'eco_friendly_products': 'Umweltfreundliche Produkte',
      'nutrition_overview': 'Ernährungsübersicht',
      'organic': 'Bio',
      'fair_trade': 'Fair Trade',
      'allergen_warning': 'Enthält Allergene',
      'may_contain': 'Kann enthalten',
      'dietary_info': 'Ernährungsinformation',
      'certifications': 'Zertifizierungen',
      'goals': 'Ziele',
      'bottom_nav_goals': 'Ziele',
      'weekly_progress': 'Wöchentlicher Fortschritt',
      'healthy_choices': 'gesunde Entscheidungen diese Woche',
      'eco_friendly': 'Umweltfreundlich',
      'eco_friendly_choices': 'umweltfreundliche Entscheidungen',
      'healthy_streak': 'Gesunde Serie',
      'healthy_products': 'gesunde Produkte',
      'nutriscore_distribution': 'Nutriscore-Verteilung',
      'tips_for_improvement': 'Tipps zur Verbesserung',
      'tip_1_title': 'Mehr A und B Produkte Wählen',
      'tip_1_description': 'Produkte mit Nutriscore A und B sind im Allgemeinen gesündere Optionen.',
      'tip_2_title': 'Pflanzlich Ernähren',
      'tip_2_description': 'Versuchen Sie, mehr vegetarische und vegane Produkte in Ihre Ernährung einzubauen.',
      'tip_3_title': 'Zusatzstoffe Beachten',
      'tip_3_description': 'Wählen Sie wenn möglich Produkte mit weniger künstlichen Zusatzstoffen.',
      'education': 'Bildung',
      'bottom_nav_education': 'Lernen',
      'education_intro': 'Erfahren Sie mehr über Nährstoffe, Zutaten und gesündere Lebensmittelauswahl.',
      'daily_nutrition_facts': 'Tägliche Nährwert-Fakten',
      'daily_nutrition_facts_desc': 'Erfahren Sie mehr über essentielle Nährstoffe und tägliche empfohlene Werte.',
      'ingredient_encyclopedia': 'Zutaten-Enzyklopädie',
      'ingredient_encyclopedia_desc': 'Detaillierte Informationen zu häufig verwendeten Lebensmittelzutaten und Zusatzstoffen.',
      'understanding_labels': 'Lebensmittel-Label verstehen',
      'understanding_labels_desc': 'Leitfaden zum Lesen und Verstehen von Nährwert- und Zusatzstoff-Deklarationen.',
      'healthy_tips': 'Tipps für gesündere Auswahlen',
      'healthy_tips_desc': 'Praktische Tipps für gesündere Lebensmittelauswahl.',
      'nutrition_quizzes': 'Nährwert-Quizze',
      'nutrition_quizzes_desc': 'Testen Sie Ihr Wissen über Nährstoffe und Lebensmittel.',
      'seasonal_guide': 'Saisonale Lebensmittel-Guide',
      'seasonal_guide_desc': 'Erfahren Sie mehr über saisonale Früchte und Gemüse.',
      'eco_packaging': 'Öko-Verpackung',
      'eco_packaging_desc': 'Verstehen Sie Lebensmittel-Verpackungen und ihr Umwelt-Einfluss.',
      'feature_coming_soon': 'Diese Funktion ist bald verfügbar!',
      'daily_intake_title': 'Empfohlene Tageszufuhr',
      'daily_intake_content': 'Ein durchschnittlicher Erwachsener benötigt etwa 2000-2500 Kalorien pro Tag, aber dies variiert je nach Alter, Geschlecht, Gewicht, Aktivitätsniveau und anderen Faktoren.',
      'macronutrients_title': 'Verteilung der Makronutrienten',
      'macronutrients_content': 'Eine ausgewogene Ernährung besteht typischerweise aus: 45-65% Kohlenhydrate, 20-35% Fette und 10-35% Proteine. Cette répartition aide à maintenir un bon fonctionnement corporel et des niveaux d\'énergie.',
      'vitamins_minerals_title': 'Vitaminas y Minéraux Essenciais',
      'vitamins_minerals_content': 'Os micronutrientes principais incluem Vitamina D, B12, Ferro, Cálcio e Zinco. Estes apoiam a função imune, saúde óssea e metabolismo energético.',
      'hydration_title': 'Hydratation',
      'hydration_content': 'Procure beber 8 copos (cerca de 2 litros) de água por dia. As necessidades aumentam com exercício, clima quente ou certas condições médicas.',
      'additives_title': 'Häufige Zusatzstoffe',
      'additives_content': 'E-Nummern sind Codes für Lebensmittelzusätze. Während viele sicher sind, können einige bei empfindlichen Personen Reaktionen hervorrufen. Häufige sind E330 (Zitronensäure) und E300 (Vitamin C).',
      'natural_artificial_title': 'Natürlich vs. Künstlich',
      'natural_artificial_content': 'Natürliche Zutaten stammen direkt von Pflanzen oder Tieren. Künstliche Zutaten werden in Laboren synthetisiert. Keines ist von Natur aus gut oder schlecht - die Sicherheit hängt von spezifischen Eigenschaften und Verwendung ab.',
      'hidden_sugars_title': 'Versteckte Zucker',
      'hidden_sugars_content': 'Zucker kann unter vielen Namen erscheinen: Glukose, Fruktose, Dextrose, Maltose, Maissirup und mehr. Bewusstsein hilft, die Gesamtzuckeraufnahme zu überwachen.',
      'preservatives_title': 'Konservierungsstoffe',
      'preservatives_content': 'Häufige Konservierungsmittel sind Sulfite, Nitrite und Benzoate. Während sie Lebensmittel länger haltbar machen, können manche Menschen auf bestimmte Arten empfindlich reagieren.',
      'nutrition_panel_title': 'Nährwerttabelle',
      'nutrition_panel_content': 'Zeigt Portionsgröße, Kalorien und Nährstoffgehalt. Werte werden typischerweise pro 100g und pro Portion angegeben, um Produkte vergleichen zu können.',
      'ingredient_list_title': 'Zutatenliste',
      'ingredient_list_content': 'Zutaten sind nach Gewicht aufgelistet, von der größten zur kleinsten Menge. Dies hilft zu verstehen, woraus das Produkt hauptsächlich besteht.',
      'health_claims_title': 'Gesundheitsbezogene Angaben',
      'health_claims_content': 'Begriffe wie "fettarm" oder "ballaststoffreich" sind reguliert. Zum Beispiel bedeutet "fettarm" 3g oder weniger pro 100g bei Feststoffen.',
      'allergen_info_title': 'Allergeninformation',
      'allergen_info_content': 'Häufige Allergene müssen deutlich gekennzeichnet sein. Sie können fett gedruckt oder in einer separaten "Enthält"-Angabe erscheinen.',
      'balanced_plate_title': 'Ausgewogener Teller',
      'balanced_plate_content': 'Füllen Sie die Hälfte Ihres Tellers mit Gemüse, ein Viertel mit magerem Protein und ein Viertel mit Vollkornprodukten für eine ausgewogene Mahlzeit.',
      'smart_shopping_title': 'Intelligentes Einkaufen',
      'smart_shopping_content': 'Kaufen Sie zuerst am Rand des Geschäfts ein - dort befinden sich meist frische, unverarbeitete Lebensmittel. Lesen Sie Etiketten vor dem Kauf verpackter Lebensmittel.',
      'meal_prep_title': 'Mahlzeitenvorbereitung',
      'meal_prep_content': 'Bereiten Sie Mahlzeiten im Voraus zu, um ungesunde Fertiggerichte zu vermeiden. Verwenden Sie Kräuter und Gewürze statt Salz zum Würzen.',
      'mindful_eating_title': 'Achtsames Essen',
      'mindful_eating_content': 'Essen Sie langsam, ohne Ablenkung. Dies hilft, Sättigungssignale zu erkennen und verbessert die Verdauung.',
      'spring_title': 'Frühling',
      'spring_content': 'Achten Sie auf Spargel, Erbsen, Erdbeeren und Blattgemüse. Diese Lebensmittel sind von Natur aus reich an Vitaminen und Mineralstoffen, die für Energie benötigt werden, wenn die Tage länger werden.',
      'summer_title': 'Sommer',
      'summer_content': 'Genießen Sie Tomaten, Paprika, Beeren und Steinobst. Sommerprodukte sind reich an Antioxidantien und naturalerweise hydrierend.',
      'fall_title': 'Herbst',
      'fall_content': 'Wählen Sie Kürbisse, Äpfel, Birnen und Wurzelgemüse. Diese Lebensmittel liefern anhaltende Energie und Immununterstützung für kühleres Wetter.',
      'winter_title': 'Winter',
      'winter_content': 'Wählen Sie Zitrusfrüchte, Winterkürbis und Kreuzblütler. Diese Lebensmittel sind reich an Vitamin C und anderen Nährstoffen zur Unterstützung der Wintergesundheit.',
      'packaging_symbols_title': 'Verpackungssymbole',
      'packaging_symbols_content': 'Lernen Sie, recycelbare Materialien anhand von Verpackungssymbolen zu erkennen. Die Nummer im Recyclingsymbol gibt den verwendeten Kunststofftyp an.',
      'sustainable_materials_title': 'Nachhaltige Materialien',
      'sustainable_materials_content': 'Suchen Sie nach Produkten in Glas-, Aluminium- oder Kartonverpackungen. Esses Materialien haben hohe Recyclingraten und geringere Umweltauswirkungen.',
      'reducing_waste_title': 'Abfallreduzierung',
      'reducing_waste_content': 'Wählen Sie Produkte mit minimaler Verpackung oder Großpackungen. Bringen Sie wiederverwendbare Taschen und Behälter zum Einkaufen mit.',
      'proper_disposal_title': 'Sachgerechte Entsorgung',
      'proper_disposal_content': 'Reinigen Sie Behälter vor dem Recycling. Verschiedene Materialien müssen möglicherweise getrennt werden. Prüfen Sie lokale Recyclingrichtlinien für spezifische Anforderungen.',
      'product_details_singular': 'Produktdetails',
      'product_details_plural': 'Produktdetails',
      'other_high_risk_additives': 'Weitere Zusatzstoffe mit hohem Risiko',
      'other_high_risk_additives_desc': '{count} weitere Zusatzstoffe oder Süßungsmittel mit hohem Risiko',
      'other_moderate_risk_additives': 'Weitere Zusatzstoffe mit mittlerem Risiko',
      'other_moderate_risk_additives_desc': '{count} weitere Zusatzstoffe mit mittlerem Risiko',
      'other_low_risk_additives': 'Weitere Zusatzstoffe mit niedrigem Risiko',
      'other_low_risk_additives_desc': '{count} weitere Zusatzstoffe mit niedrigem Risiko',
      'unidentified': 'Nicht Identifiziert',
      'sweetener': 'Süßungsmittel',
      'color': 'Farbstoff',
      'preservative': 'Konservierungsmittel',
      'antioxidant': 'Antioxidationsmittel',
      'emulsifier': 'Emulgator',
      'thickener': 'Verdickungsmittel',
      'stabilizer': 'Stabilisator',
      'acid': 'Säure',
      'flavoring': 'Geschmacksstoff',
      'additive': 'Zusatzstoff',
      'no_ingredients': 'Keine Zutaten aufgeführt',
      'themes': 'Designs',
      'select_theme': 'Design Auswählen',
      'purple': 'Lila',
      'green': 'Grün',
      'orange': 'Orange',
      'blue': 'Blau',
      'grey': 'Grau',
      'sign_in': 'Anmelden',
      'sign_out': 'Abmelden',
    },
    'pt': {
      'scan': 'Digitalizar',
      'history': 'Histórico',
      'search': 'Procurar',
      'search_hint': 'Pesquisar seus produtos digitalizados',
      'search_helper_text': 'Try entering a product name (e.g., "Oreo") or brand name (e.g., "Nestle")',
      'search_examples': 'Examples: "Coca Cola", "Nutella", "Lay\'s Chips", "5449000000996"',
      'openfoodfacts_info': 'Search uses OpenFoodFacts database. If a product isn\'t found, try scanning its barcode instead.',
      'try_again': 'Tentar Novamente',
      'start_searching': 'Comece a digitar para procurar produtos',
      'no_results': 'Nenhum produto encontrado',
      'favorites': 'Favoritos',
      'profile': 'Perfil',
      'settings': 'Definições',
      'dietary_preferences': 'Preferências Alimentares',
      'notifications': 'Notificações',
      'notifications_enabled': 'Ativar Notificações',
      'language': 'Idioma',
      'dark_mode': 'Modo Escuro',
      'about': 'Sobre',
      'about_description': 'O NutriScan ajuda-o a tomar decisões informadas sobre os alimentos que consome. Basta digitalizar códigos de barras dos produtos para obter informações nutricionais detalhadas, alertas de alergénios e compatibilidade alimentar.',
      'version': 'Versão',
      'none_selected': 'Nenhum selecionado',
      'select_language': 'Selecionar Idioma',
      'done': 'Concluído',
      'nutritional_values': 'Valores Nutricionais',
      'ingredients': 'Ingredientes',
      'allergens': 'Alergénios',
      'per_100g': 'por 100g',
      'per_serving': 'por {serving}',
      'energy': 'Energia',
      'fat': 'Gorduras',
      'saturated_fat': 'Gorduras Saturadas',
      'carbohydrates': 'Hidratos de Carbono',
      'sugars': 'Açúcares',
      'proteins': 'Proteínas',
      'salt': 'Sal',
      'fiber': 'Fibra',
      'dietary_warning': 'Aviso de Preferências Alimentares',
      'additives': 'Aditivos',
      'additives_warning': 'Informação de Aditivos',
      'risk_level': 'Nível de Risco',
      'low_risk': 'Baixo Risco',
      'moderate_risk': 'Risco Moderado',
      'high_risk': 'Risco Alto',
      'unknown_risk': 'Risco Desconhecido',
      'no_additives': 'Nenhum aditivo encontrado',
      'not_suitable': 'Este produto não é adequado para a sua',
      'diet': 'dieta',
      'diets': 'dietas',
      'vegetarian': 'Vegetariano',
      'vegan': 'Vegano',
      'gluten_free': 'Sem Glúten',
      'lactose_free': 'Sem Lactose',
      'nut_free': 'Sem Frutos Secos',
      'palm_oil_free': 'Sem Óleo de Palma',
      'scan_product': 'Digitalizar Produto',
      'scan_barcode': 'Digitalize o código de barras',
      'camera_permission': 'Permissão de câmara necessária',
      'grant_permission': 'Conceder Permissão',
      'search_products': 'Procurar Produtos',
      'no_favorites': 'Sem produtos favoritos',
      'no_history': 'Sem histórico',
      'clear_history': 'Limpar Histórico',
      'clear_history_confirm': 'Tem a certeza que pretende limpar o histórico?',
      'cancel': 'Cancelar',
      'clear': 'Limpar',
      'unknown_brand': 'Marca Desconhecida',
      'search_error': 'Erro ao procurar produtos',
      'bottom_nav_scan': 'Digitalizar',
      'bottom_nav_history': 'Histórico',
      'bottom_nav_search': 'Procurar',
      'bottom_nav_favorites': 'Favoritos',
      'bottom_nav_profile': 'Perfil',
      'bottom_nav_overview': 'Visão Geral',
      'bottom_nav_recommendations': 'Recomendaciones',
      'bottom_nav_compare': 'Comparar',
      'compare': 'Comparar Productos',
      'comparison_instructions': 'Selecione dois produtos para comparar seus valores nutricionais',
      'select_product': 'Selecionar Produto',
      'no_products_to_compare': 'Nenhum produto disponível para comparar. Escaneie ou marque alguns produtos como favoritos primeiro.',
      'product_1_details': 'Detalhes do Produto 1',
      'product_2_details': 'Detalhes do Produto 2',
      'product_details': 'Detalhes do Produto',
      'select_product_for_details': 'Selecione um produto para ver seus detalhes',
      'remove': 'Remover',
      'overview': 'Visão Geral',
      'scan_statistics': 'Estatísticas de Digitalização',
      'total_scans': 'Total de Digitalizações',
      'total_favorites': 'Total de Favoritos',
      'eco_friendly_products': 'Produtos Ecológicos',
      'nutrition_overview': 'Visão Geral Nutricional',
      'organic': 'Orgânico',
      'fair_trade': 'Comércio Justo',
      'allergen_warning': 'Contém alergénios',
      'may_contain': 'Pode conter',
      'dietary_info': 'Informação Nutricional',
      'certifications': 'Certificações',
      'goals': 'Objetivos',
      'bottom_nav_goals': 'Objetivos',
      'weekly_progress': 'Progresso Semanal',
      'healthy_choices': 'escolhas saudáveis esta semana',
      'eco_friendly': 'Ecológico',
      'eco_friendly_choices': 'escolhas ecológicas',
      'healthy_streak': 'Sequência Saudável',
      'healthy_products': 'produtos saudáveis',
      'nutriscore_distribution': 'Distribuição Nutriscore',
      'tips_for_improvement': 'Dicas para Melhorar',
      'tip_1_title': 'Escolha Mais Produtos A e B',
      'tip_1_description': 'Produtos com Nutriscore A e B são geralmente escolhas mais saudáveis.',
      'tip_2_title': 'Opte por Vegetais',
      'tip_2_description': 'Tente incorporar mais produtos vegetarianos e veganos em sua dieta.',
      'tip_3_title': 'Controle os Aditivos',
      'tip_3_description': 'Escolha produtos com menos aditivos artificiais quando possível.',
      'education': 'Educação',
      'bottom_nav_education': 'Aprender',
      'education_intro': 'Aprenda mais sobre nutrientes, ingredientes e escolher alimentos mais saudáveis.',
      'daily_nutrition_facts': 'Fatos Nutricionais Diários',
      'daily_nutrition_facts_desc': 'Aprenda mais sobre nutrientes essenciais e valores recomendados diários.',
      'ingredient_encyclopedia': 'Enciclopédia de Ingredientes',
      'ingredient_encyclopedia_desc': 'Informações detalhadas sobre ingredientes alimentares comuns e aditivos.',
      'understanding_labels': 'Entendendo Rótulos de Alimentos',
      'understanding_labels_desc': 'Guia para ler e entender declarações e reivindicações nutricionais.',
      'healthy_tips': 'Dicas para Escolhas Mais Saudáveis',
      'healthy_tips_desc': 'Conselhos práticos para fazer melhores escolhas alimentares.',
      'nutrition_quizzes': 'Questionários de Nutrição',
      'nutrition_quizzes_desc': 'Teste seu conhecimento sobre nutrição e alimentos.',
      'seasonal_guide': 'Guia de Alimentos Sazonais',
      'seasonal_guide_desc': 'Aprenda mais sobre frutas e vegetais sazonais.',
      'eco_packaging': 'Embalagem Ecológica',
      'eco_packaging_desc': 'Entendendo embalagens de alimentos e seu impacto ambiental.',
      'feature_coming_soon': 'Esta funcionalidade está chegando!',
      'daily_intake_title': 'Ingestão Diária Recomendada',
      'daily_intake_content': 'Um adulto médio precisa de aproximadamente 2000-2500 calorias por dia, mas isso varia com base na idade, sexo, peso, nível de atividade e outros fatores.',
      'macronutrients_title': 'Distribuição de Macronutrientes',
      'macronutrients_content': 'Uma dieta equilibrada tipicamente consiste em: 45-65% carboidratos, 20-35% gorduras e 10-35% proteínas. Esta distribuição ajuda a manter o funcionamento adequado do corpo e os níveis de energia.',
      'vitamins_minerals_title': 'Vitaminas e Minerais Essenciais',
      'vitamins_minerals_content': 'Os micronutrientes principais incluem Vitamina D, B12, Ferro, Cálcio e Zinco. Estes apoiam a função imune, saúde óssea e metabolismo energético.',
      'hydration_title': 'Hidratação',
      'hydration_content': 'Procure beber 8 copos (cerca de 2 litros) de água por dia. As necessidades aumentam com exercício, clima quente ou certas condições médicas.',
      'additives_title': 'Aditivos Comuns',
      'additives_content': 'Números E são códigos para aditivos alimentares. Embora muitos sejam seguros, alguns podem causar reações em indivíduos sensíveis. Os comuns incluem E330 (Ácido Cítrico) e E300 (Vitamina C).',
      'natural_artificial_title': 'Natural vs. Artificial',
      'natural_artificial_content': 'Ingredientes naturais vêm diretamente de plantas ou animais. Ingredientes artificiais são sintetizados em laboratórios. Nenhum é inerentemente bom ou ruim - a segurança depende de propriedades específicas e uso.',
      'hidden_sugars_title': 'Açúcares Ocultos',
      'hidden_sugars_content': 'O açúcar pode aparecer sob muitos nomes: glicose, frutose, dextrose, maltose, xarope de milho e mais. Estar ciente ajuda a monitorar a ingestão total de açúcar.',
      'preservatives_title': 'Conservantes',
      'preservatives_content': 'Conservantes comuns incluem sulfitos, nitritos e benzoatos. Embora mantenham os alimentos seguros por mais tempo, algumas pessoas podem ser sensíveis a certos tipos.',
      'nutrition_panel_title': 'Painel de Informação Nutricional',
      'nutrition_panel_content': 'Mostra tamanho da porção, calorias e conteúdo nutricional. Valores são tipicamente mostrados por 100g e por porção para ajudar a comparar produtos.',
      'ingredient_list_title': 'Lista de Ingredientes',
      'ingredient_list_content': 'Ingredientes são listados por peso, do maior ao menor. Isso ajuda a entender o que compõe a maioria do produto.',
      'health_claims_title': 'Alegações de Saúde',
      'health_claims_content': 'Termos como "baixo teor de gordura" ou "rico em fibras" são regulamentados. Por exemplo, "baixo teor de gordura" significa 3g ou menos por 100g para sólidos.',
      'allergen_info_title': 'Informação sobre Alergênicos',
      'allergen_info_content': 'Alergênicos comuns devem ser claramente rotulados. Podem aparecer em negrito ou em uma declaração "Contém" separada.',
      'balanced_plate_title': 'Prato Equilibrado',
      'balanced_plate_content': 'Preencha metade do seu prato com vegetais, um quarto com proteínas magras e um quarto com grãos integrais para uma refeição equilibrada.',
      'smart_shopping_title': 'Compras Inteligentes',
      'smart_shopping_content': 'Compre primeiro no perímetro da loja - é onde geralmente ficam os alimentos frescos e integrais. Leia rótulos antes de comprar alimentos embalados.',
      'meal_prep_title': 'Preparação de Refeições',
      'meal_prep_content': 'Prepare refeições com antecedência para evitar alimentos não saudáveis por conveniência. Use ervas e especiarias em vez de sal para temperar.',
      'mindful_eating_title': 'Alimentação Consciente',
      'mindful_eating_content': 'Coma devagar, sem distrações. Isso ajuda a reconhecer sinais de saciedade e melhora a digestão.',
      'spring_title': 'Primavera',
      'spring_content': 'Procure aspargos, ervilhas, morangos e verduras. Esses alimentos são naturalmente ricos em vitaminas e minerais necessários para energia quando os dias ficam mais longos.',
      'summer_title': 'Verão',
      'summer_content': 'Aproveite tomates, pimentões, frutas vermelhas e frutas com caroço. Os produtos de verão são ricos em antioxidantes e naturalmente hidratantes.',
      'fall_title': 'Outono',
      'fall_content': 'Escolha abóboras, maçãs, peras e vegetais de raiz. Esses alimentos fornecem energia sustentada e suporte imunológico para o clima mais frio.',
      'winter_title': 'Inverno',
      'winter_content': 'Selecione cítricos, abóbora de inverno e vegetais crucíferos. Esses alimentos são ricos em vitamina C e outros nutrientes para apoiar a saúde no inverno.',
      'packaging_symbols_title': 'Símbolos de Embalagem',
      'packaging_symbols_content': 'Aprenda a identificar materiais recicláveis através de símbolos de embalagem. O número dentro do símbolo de reciclagem indica o tipo de plástico usado.',
      'sustainable_materials_title': 'Materiais Sustentáveis',
      'sustainable_materials_content': 'Procure produtos em embalagens de vidro, alumínio ou papelão. Esses materiais têm altas taxas de reciclagem e menor impacto ambiental.',
      'reducing_waste_title': 'Redução de Resíduos',
      'reducing_waste_content': 'Escolha produtos com embalagem mínima ou opções a granel. Traga sacolas e recipientes reutilizáveis ao fazer compras.',
      'proper_disposal_title': 'Descarte Adequado',
      'proper_disposal_content': 'Limpe os recipientes antes de reciclar. Diferentes materiais podem precisar ser separados. Verifique as diretrizes locais de reciclagem para requisitos específicos.',
      'product_details_singular': 'Detalhes do Produto',
      'product_details_plural': 'Detalhes dos Produtos',
      'other_high_risk_additives': 'Outros Aditivos de Alto Risco',
      'other_high_risk_additives_desc': '{count} aditivos ou adoçantes adicionais de alto risco',
      'other_moderate_risk_additives': 'Outros Aditivos de Risco Moderado',
      'other_moderate_risk_additives_desc': '{count} aditivos adicionais de risco moderado',
      'other_low_risk_additives': 'Outros Aditivos de Baixo Risco',
      'other_low_risk_additives_desc': '{count} aditivos adicionais de baixo risco',
      'unidentified': 'Não Identificado',
      'sweetener': 'Adoçante',
      'color': 'Corante',
      'preservative': 'Conservante',
      'antioxidant': 'Antioxidante',
      'emulsifier': 'Emulsificante',
      'thickener': 'Espessante',
      'stabilizer': 'Estabilizador',
      'acid': 'Ácido',
      'flavoring': 'Aromatizante',
      'additive': 'Aditivo',
      'no_ingredients': 'Nenhum ingrediente listado',
      'themes': 'Temas',
      'select_theme': 'Definir Tema',
      'purple': 'Roxo',
      'green': 'Verde',
      'orange': 'Laranja',
      'blue': 'Azul',
      'grey': 'Cinza',
      'sign_in': 'Entrar',
      'sign_out': 'Sair',
    },
  };

  String translate(String key, [Map<String, String>? params]) {
    final translation = _localizedValues[locale.languageCode]?[key] ?? key;
    if (params != null) {
      return translation.replaceAllMapped(
        RegExp(r'\{(\w+)\}'),
        (match) => params[match.group(1)] ?? match.group(0)!,
      );
    }
    return translation;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'es', 'fr', 'de', 'pt'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
} 